language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: ZLcNQO3KwIaeaZfB4PqDmKIKCrkv8CyutFlPg9VQ7jMtQ4xJ/nEXxZ8fRM0aiwPEF/HdbGI0LTSQ8YHMX+NqMW+W9DfVwG27IXxrc29Kxjzstb7it6YlsJbYxeajFw26Mdme4IXb7gMnNmVWyCUa9Z273FmftDFhfQsnWqvCoeI=
  - secure: XU6W5Nw8uEdVgKWvZv10hsWAnjJn9Qree+vCZ/pjtIczqkis51rWaNtf4n3hMV2yzhXr2D0S0WTS48i+hJexzbKOMFaRZjQu9is2D7bltVc+o5wms7YnZeGo6sOD6DEZFdoy8hjRcNgfd6SYmOLKOlH/iJgaaAy53OBsDcV54f4=
  - secure: Y3/CMXdAorNVVYmZUersyYoVsf7tWkOvPRxDbHqqsm4EnljvzPDELczJjJixGXFPpgf/Z2qiUlJ55QVu7V1ql6eMftqx9c9g/A3J0Oh+X2cgQNGt5A20Mi8CAPMnRd38fGUhxyLkuLdchwfgTkwENLVsD4aW94ETdMEZ2vDOqDc=
  - secure: aWc5jHZwryLo3N3opPGARSuenStd0zDl2kno1WSuu5Em3Iw+XSweYcT9R2nLVwFKZ7KlrdSxvTUVsprPY94/AhDV75kzNYri/4LumJomKbpabUnHXtEEzDlr3QdA9F9Z8CqV54mIqn4xsBy/596DT65htQN5RDbbMENKbDf5xRc=
